### PR TITLE
correct input cnxml for xsl tests to be valid

### PR DESCRIPTION
**Pull request by reedstrm**
validated all input CNXML files with jing and 0.7 rng schema. Cascaded fixes. Mostly missing required Ids, some cases of mis-matched attributes, or bad context (e.g. wrap tags that can't be top level in a para)

This does not validate the round-tripped cnxml->html->cnxml files, yet.

### CODE REVIEW

**Comment by edwoodward** [comment]
What problem is this solving?

**Comment by reedstrm** [comment]
valid tests need to start with valid input.

**Comment by pumazi** [comment]
This probably needs to be split into two commits. There are two things going on here. I'm seeing the addition of a id generator xsl that changes the markup of the test data, but then there is also what looks to be a change from ``<para>`` to ``<note>``.

**Comment by karenc** [comment]
Everything is now in #139.

**Comment by karenc** [comment]
Doing everything in one patch made it difficult to review.  I spent a few hours splitting it into separate commits that are easy to review, revert or bisect.  Please try to do with your own pull requests in the future too.

**Comment by reedstrm** [comment]
I noticed. Thanks.

**Pull request closed without merging**
