### PR TITLE
treat cite-with-reference as a link

### PR DESCRIPTION
**Pull request by reedstrm**
This handles cite tags with link-like attributes by converting to links.

### CODE REVIEW

**Comment by pumazi** [comment]
Can you add to the test to verify the *xsl:otherwise* path?

**Comment by pumazi** [comment]
The html -> cnxml transform is just works?

**Comment by reedstrm** [comment]
The existing tests do test both branches: with and without a ref. of some sort. Yes, the back conversion seems to be correct as it stands.

**Comment by reedstrm** [comment]
hold off a bit, I'm making sure about the round trip right now.

**Comment by reedstrm** [comment]
Back conversions now complete

**Pull request merged**
