### PR TITLE
Transform fixes

### LINKED ISSUE #112: HTML to CNXML Transform - Summary contains divs that are not converted
I published a Page on beta.cnx.org and I did not enter a Summary. On legacybeta, the Summary is displaying 4 not converted divs.

See http://legacybeta.cnx.org/content/m53198/1.5/?legacy=true

### PR DESCRIPTION
**Pull request by karenc**
Fix #112, #113, #114

### CODE REVIEW

**Comment by pumazi** [comment]
I'm not so sure about this ``@data-type='description'`` commit. I think webview may be wrong to put a data-type on it.

**Comment by karenc** [comment]
I think so too.  Also, looking at the html generated by webview here http://betaarchive.cnx.org/contents/4fcecc4c-cda3-4ee2-9034-65398cc26ace@1.html, webview might still be using `class` instead of `data-type` for title:

```xml
<div class="title" id="989b1ea2-9f98-2bbd-a51e-32ec96d51b88"/>
```

**Comment by pumazi** [comment]
I'll double check that webview is adding titles as ``@class='title'``. If so, I'll file an issue in webview.

**Comment by pumazi** [comment]
Issue filed for incorrect title labeling at Connexions/webview#919

I also noticed that some of the block components (note, example, etc.) are all using ``@class=<type>`` rather than ``@data-type=<type>``.

**Comment by reedstrm** [comment]
@pumazi Go ahead and make those changes, I'll review.

**Comment by reedstrm** [comment]
As per scrum discussion, the remaining data- vs. class issues we see here will damage round-tripping, but are properly filed as webvew/editor bugs, so we'll merge this code and move on.

**Pull request merged**
