### PR TITLE
:bug: remove class="TYPE" in favor of just data-type="type"

### PR DESCRIPTION
**Pull request by philschatz**
The HS Physics book contains an end-of-chapter collated section named `class="problem"` which conflicts with exercises (they also contain a `class="problem"` because of the `<problem>` element).

The type of the element (`<cnx:problem>`) was being duplicated (as `<div data-type="problem" class="problem">`) and this PR removes that duplication.

Refs https://github.com/Connexions/cnx-recipes/pull/112

/cc @helenemccarron

### CODE REVIEW

**Comment by pumazi** [comment]
Is this still something we need to pursue? If it is, can you ( @philschatz ) resolve the failing tests?

**Comment by philschatz** [comment]
@pumazi I tried fixing the failing tests but there is a whitespace issue when regenerating the tests on OSX (I seem to recall). 

Could you or @reedstrm run `./scripts/rebuild-tests` and commit?

**Comment by reedstrm** [comment]
I'll give it a try

**Comment by reedstrm** [comment]
re-running scrt awas not sufficient - I had to hand-edit the output. There's something slightly different about how the tests run compared to the build script it seems.

**Comment by reedstrm** [comment]
Since this now passes tests, merging.

**Pull request merged**
