### PR TITLE
Py3

### PR DESCRIPTION
**Pull request by karenc**
- Remove stale test for a feature not used in later versions.

- Fix installation manifest and include the lxml dependency for >= py2.7

- Add tox configuration for running tests against py2.7 and py3.4

- Update tests to be python3 compatible

- Update travis to run tests against py2.7 and py3.4

### CODE REVIEW

**Comment by reedstrm** [comment]
Karen we seem to be chasing each other around. I spent yesterday working on the tests in xsl/test :-) Will PR today.

**Comment by karenc** [comment]
Ah... ;D  This was actually written a looong time ago, I thought we should probably merge it soon.

**Comment by reedstrm** [comment]
Is the 'switching things to binary' the best approach? When I see having to open expected output files with 'rb' and manually splitting them on '\n', I wonder ...

**Comment by karenc** [comment]
When opening files without "rb", we get back a python3 string, with "rb", we get back bytes.  `subprocess` works only with bytes, so I think that's why "rb" was added to `open`.

As for manually splitting them on "\n", it seems `assertMultiLineEqual` doesn't work with bytes, so either we split the lines manually, or do `self.assertMultiLineEqual(output.decode('utf-8'), html.decode('utf-8'))`.

**Pull request merged**
